### PR TITLE
Update to chia-blockchain 1.8

### PR DESCRIPTION
**Pull request by jack60612**

### CODE REVIEW

**Review by hoffmang9 — APPROVED** [review]
Lgtm

**Comment by hoffmang9** [comment]
Well, maybe not lgtm since all the tests failed.

**Comment by jack60612** [comment]
> Well, maybe not lgtm since all the tests failed.

i was about to say.

**Review by hoffmang9 — CHANGES_REQUESTED** [review]
Let's see if this cancels my approval. Get those tests working first.

**Review by hoffmang9 — APPROVED** [review]
Now lgtm

**Pull request merged**
