### PR TITLE
Add an option to plot without bitfield

### PR DESCRIPTION
**Pull request by Quexington**
https://github.com/Chia-Network/chia-dev-tools/issues/47

### CODE REVIEW

**Comment by Quexington** [comment]
This needs to be rebased when https://github.com/Chia-Network/chia-dev-tools/pull/56 lands

**Comment by jack60612** [comment]
Thanks, i forgot to do this on this side

**Comment by Quexington** [comment]
Oh hmm I think I interpreted the issue backwards you might be right.

**Comment by jack60612** [comment]
> Oh hmm I think I interpreted the issue backwards you might be right.

did you close wrong pr?

**Review by jack60612 — APPROVED** [review]

**Pull request merged**
