### PR TITLE
Revert to old installation method + Remove Simulator

### PR DESCRIPTION
**Pull request by jack60612**
add regex for main tests

### CODE REVIEW

**Comment by jack60612** [comment]
Failure is expected.

**Comment by jack60612** [comment]
supersedes #75

**Review by wallentx — APPROVED** [review]

**Review by Quexington — APPROVED** [review]

**Comment by wizicer** [comment]
Why have the simulator removed? Any other way to get the simulator?

**Comment by hoffmang9** [comment]
It is now over in chia-blockchain

**Pull request merged**
